### ISSUE TITLE
HTML에서 script 태그의 위치

### ISSUE THREAD

**Issue by crystal025** [SLOW-STEADY-CLUB/JS-ST-1#1]
<img width="558" alt="스크린샷 2022-12-02 오후 10 25 07" src="https://user-images.githubusercontent.com/109053875/205302822-82ce26e6-fb24-44f8-942e-24dafed70424.png">

<img width="545" alt="스크린샷 2022-12-02 오후 10 25 25" src="https://user-images.githubusercontent.com/109053875/205302856-af32d535-b7ec-4778-8f00-a094b9d3af44.png">

body 태그 아래에 위치하는 것이 좋다고 합니다.

**Comment by 0gunkim** [comment]
#7 덕분에 공부해서 완벽이해 했습니다. 고맙습니다

**Comment by hakyunglee** [comment]
👍
